(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.turf = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var linestring=require("turf-linestring"),Spline=require("./spline.js");module.exports=function(r,e,n){var i=linestring([]);i.properties=r.properties;for(var o=r.geometry.coordinates.map(function(r){return{x:r[0],y:r[1]}}),t=new Spline({points:o,duration:e,sharpness:n}),s=0;s<t.duration;s+=10){var p=t.pos(s);Math.floor(s/100)%2===0&&i.geometry.coordinates.push([p.x,p.y])}return i};

},{"./spline.js":2,"turf-linestring":3}],2:[function(require,module,exports){
var Spline=function(s){this.points=s.points||[],this.duration=s.duration||1e4,this.sharpness=s.sharpness||.85,this.centers=[],this.controls=[],this.stepLength=s.stepLength||60,this.length=this.points.length,this.delay=0;for(var t=0;t<this.length;t++)this.points[t].z=this.points[t].z||0;for(var t=0;t<this.length-1;t++){var i=this.points[t],h=this.points[t+1];this.centers.push({x:(i.x+h.x)/2,y:(i.y+h.y)/2,z:(i.z+h.z)/2})}this.controls.push([this.points[0],this.points[0]]);for(var t=0;t<this.centers.length-1;t++){var i=this.centers[t],h=this.centers[t+1],n=this.points[t+1].x-(this.centers[t].x+this.centers[t+1].x)/2,e=this.points[t+1].y-(this.centers[t].y+this.centers[t+1].y)/2,r=this.points[t+1].z-(this.centers[t].y+this.centers[t+1].z)/2;this.controls.push([{x:(1-this.sharpness)*this.points[t+1].x+this.sharpness*(this.centers[t].x+n),y:(1-this.sharpness)*this.points[t+1].y+this.sharpness*(this.centers[t].y+e),z:(1-this.sharpness)*this.points[t+1].z+this.sharpness*(this.centers[t].z+r)},{x:(1-this.sharpness)*this.points[t+1].x+this.sharpness*(this.centers[t+1].x+n),y:(1-this.sharpness)*this.points[t+1].y+this.sharpness*(this.centers[t+1].y+e),z:(1-this.sharpness)*this.points[t+1].z+this.sharpness*(this.centers[t+1].z+r)}])}return this.controls.push([this.points[this.length-1],this.points[this.length-1]]),this.steps=this.cacheSteps(this.stepLength),this};Spline.prototype.cacheSteps=function(s){var t=[],i=this.pos(0);t.push(0);for(var h=0;h<this.duration;h+=10){var n=this.pos(h),e=Math.sqrt((n.x-i.x)*(n.x-i.x)+(n.y-i.y)*(n.y-i.y)+(n.z-i.z)*(n.z-i.z));e>s&&(t.push(h),i=n)}return t},Spline.prototype.vector=function(s){var t=this.pos(s+10),i=this.pos(s-10);return{angle:180*Math.atan2(t.y-i.y,t.x-i.x)/3.14,speed:Math.sqrt((i.x-t.x)*(i.x-t.x)+(i.y-t.y)*(i.y-t.y)+(i.z-t.z)*(i.z-t.z))}},Spline.prototype.pos=function(s){function t(s,t,i,h,n){var e=function(s){var t=s*s,i=t*s;return[i,3*t*(1-s),3*s*(1-s)*(1-s),(1-s)*(1-s)*(1-s)]},r=e(s),o={x:n.x*r[0]+h.x*r[1]+i.x*r[2]+t.x*r[3],y:n.y*r[0]+h.y*r[1]+i.y*r[2]+t.y*r[3],z:n.z*r[0]+h.z*r[1]+i.z*r[2]+t.z*r[3]};return o}var i=s-this.delay;0>i&&(i=0),i>this.duration&&(i=this.duration-1);var h=i/this.duration;if(h>=1)return this.points[this.length-1];var n=Math.floor((this.points.length-1)*h),e=(this.length-1)*h-n;return t(e,this.points[n],this.controls[n][1],this.controls[n+1][0],this.points[n+1])},module.exports=Spline;

},{}],3:[function(require,module,exports){
module.exports=function(e,r){if(!e)throw new Error("No coordinates passed");return{type:"Feature",geometry:{type:"LineString",coordinates:e},properties:r||{}}};

},{}],4:[function(require,module,exports){
module.exports={bezier:require("turf-bezier")};
},{"turf-bezier":1}]},{},[4])(4)
});
